### ISSUE TITLE
[Fabric 26.2] Architectury 21.1.8 crashes dedicated server with NoClassDefFoundError: LocalPlayer

### ISSUE THREAD

**Issue by awkwardusername** [architectury/architectury#744]
After upgrading Architectury API from 21.0.7 to 21.1.8, our Fabric dedicated server fails during Architectury's `main` entrypoint. The client launches successfully with the byte-identical Architectury JAR.

### Environment

- Minecraft: 26.2
- Java: 25.0.4
- Fabric Loader: 0.19.5
- Fabric API: 0.160.0+26.2
- Architectury API: 21.1.8 (`architectury-fabric-21.1.8.jar`, Modrinth version `3iJSN9Sa`)
- Architectury JAR SHA-256: `a266a90b68e9a051c4c83f40568a875944350b2a026ead87a2b056b067465156`

These versions satisfy the dependencies declared by Architectury 21.1.8's `fabric.mod.json`.

### Actual behavior

Starting the dedicated server exits during Architectury initialization:

```text
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'architectury' at 'dev.architectury.utils.fabric.GameInstanceImpl::init'!
    at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:413)
    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:411)
    at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/player/LocalPlayer
    at knot//dev.architectury.event.EventHandler.registerCommon(EventHandler.java)
    at knot//dev.architectury.event.EventHandler.init(EventHandler.java:37)
    at knot//dev.architectury.utils.fabric.GameInstanceImpl.init(GameInstanceImpl.java:44)
    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:409)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.player.LocalPlayer
```

### Expected behavior

Architectury's common initialization should complete on a dedicated server without resolving client-only Minecraft classes.

### Investigation

[Commit `c01202589646`](https://github.com/architectury/architectury-api/commit/c01202589646a15ede0513e15e2c2d8f6721b554), included through #742, added this registration to `EventHandlerImpl.registerClient()`:

```java
ClientPreAttackCallback.EVENT.register((client, player, clickCount) ->
        InteractionEvent.CLIENT_PRE_ATTACK.invoker().preAttack(player, clickCount).isFalse());
```

Inspection of the released 21.1.8 JAR with `javap -p -v` confirms a synthetic method on the shared `dev.architectury.event.fabric.EventHandlerImpl` class whose descriptor contains the client-only type:

```text
private static boolean lambda$registerClient$17(
    net.minecraft.client.Minecraft,
    net.minecraft.client.player.LocalPlayer,
    int
);
```

The callback is not registered by `registerCommon()` itself. The evidence suggests that linkage/verification of the shared implementation class during common initialization is resolving the `LocalPlayer` descriptor. The previous 21.0.7 release's `EventHandlerImpl.class` contains neither this callback nor a `LocalPlayer` reference.

This was observed in a modpack rather than a minimal three-mod reproduction. All installed mods that declare an Architectury dependency use lower-bound ranges (`>=21.0.0` or `>=9.0.8`); none requires 21.1.8 exactly. Reverting to 21.0.7 fixes this issue for my case.
